/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pill_capsule_svgrepo_com = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_svgrepo_com = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData configuration_settings_gear_options_preferences_setting_tools_svgrepo_com = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doctor = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hearth = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_object_1 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_off = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medication = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doctor_person = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData footprint = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terms_and_conditions = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liver = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_1 = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_2 = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
